### ISSUE TITLE
Where's the download link?

### ISSUE THREAD

**Issue by spring1843** [brockgr/websaver#18]
Would you please add a downloadable link to the binary? 

I used this product before when it was on google code but it seems like the binaries are not being shipped? I think this is a good product and you should make it easy for people to use it.

I tried compiling it with xcode, but it didn't build successfully tried to fix deprecated garbage collection but failed.

**Comment by brockgr** [comment]
Github UI is a little unintuitive - the available releases are at https://github.com/brockgr/websaver/releases
