### ISSUE TITLE
Run?

### ISSUE THREAD

**Issue by ZZcat** [brockgr/websaver#19]
How do you setup and run this program?
Thanks

**Comment by mdalikazi** [comment]
You need to install XCode to run this. XCode is available for free from the App store. Download the websaver project from github by clicking "Download ZIP" on far right and open the ZIP to extract it.

Once you download and install XCode, run it from Applications
- Go to File -> Open and choose the extracted websaver folder
- XCode will open the project - If XCode gives you any prompts say Yes or OK to them
- On the left panel in XCode you will see some folders, go to "Products" folder
- Right click WebSaver.saver -> Show in Finder
- Open the WebSaver.saver file to install the screensaver
- Now you can adjust its settings and use it.

**Comment by garrekr** [comment]
I got to right clicking websaver.saver and it doesnt show up in finder....
